# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.2.0

jobs:
  setup:
    executor: continuation/default
    steps:
      - continuation/continue:
          configuration_path: setup_config.yml

workflows:
  setup:
    jobs:
      - setup
