# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

setup: true

# parameters:
#   action:
#     enum: [ci, release]
#     default: ci

orbs:
  continuation: circleci/continuation@0.2.0

jobs:
  continuous-integration:
    executor: continuation/default
    steps:
      - checkout
      - continuation/continue:
          configuration_path: ./.circleci/continuous_integration.yml

  release:
    executor: continuation/default
    steps:
      - checkout
      - continuation/continue:
          configuration_path: ./.circleci/release.yml

  # setup-with-params:
  #   executor: continuation/default
  #   steps:
  #     - continuation/continue:
  #         configuration_path: setup_config.yml
  #         parameters: "{run-build-project-one-job: true}"

workflows:
  continuous-integration:
    when:
      not:
        matches:
          pattern: "^release/.*$"
          value: << pipeline.git.branch >>
    jobs:
      - continuous-integration
        # filters:
        #   branches:
        #     ignore:
        #       - /^release\/.*/

  release:
    when:
      matches:
        pattern: "^release/.*$"
        value: << pipeline.git.branch >>
    jobs:
      - release
        # filters:
        #   branches:
        #     only:
        #       - /^release\/.*/

  # setup-with-params:
  #   jobs:
  #     - setup-with-params
