version: 2.1

jobs:
  output-text:
    docker:
      - image: cimg/base:2022.04
    parameters:
      text:
        type: string
    steps:
      - run:
          command: echo "<< parameters.text >>"

workflows:
  lint:
    jobs:
      - output-text:
          name: linting
          text: running linter

  test:
    jobs:
      - output-text:
          name: testing
          text: running tests
