version: 2.1

parameters:
  run-build-project-one-job:
    type: boolean
    default: false
  run-build-project-two-job:
    type: boolean
    default: false

jobs:
  output-text:
    docker:
      - image: cimg/base
    parameters:
      text:
        type: string
    steps:
      - run:
          command: echo "<< parameters.text >>"

workflows:
  service-1:
    when: << pipeline.parameters.run-build-project-one-job >>
    jobs:
      - output-text:
          name: build-project-one
          text: Building project_one

  service-2:
    when: << pipeline.parameters.run-build-project-two-job >>
    jobs:
      - output-text:
          name: build-project-two
          text: Building project_two

  run-integration-tests:
    when:
      or:
        [
          << pipeline.parameters.run-build-project-one-job >>,
          << pipeline.parameters.run-build-project-two-job >>,
        ]
    jobs:
      - output-text:
          name: run-integration-tests
          text: running integration tests

  run-always:
    jobs:
      - output-text:
          name: run-always
          text: running always
